# the audience for this site. even if you're not single sourcing, you still need to define an audience here.
audience: developer

# your project's title. appears in the top nav home button.
title: Acme Developers Site

# currently the version is used only in the print cover
version: 2.0

# appears above the sidebar (optional)
tagline: Guide for developers

# the base hostname & protocol for your site (everything at the .com or .org and before)
url: "http://thisisandrewjohnston.com"

# the subpath of your site. If you're publishing to the root directory, just type "". Usually set this as your project name.
baseurl: "/documentation-theme-jekyll/developer"

# this is how you will preview the site on your local machine. leave as is.
host: 127.0.0.1

# specified here in case you have multiple sites and want to view them simultaneously in different tabs (you'll need different ports)
port: 4000

# whether you want the sidebar to use an accordion, such that other sections collapse when one expands.
sidebar_accordion: true

# Disqus shortname for commenting features. leave blank if you don't want a comment form.
disqus_shortname: idrbwjekyll

# Insert your google analytics tracking number. leave blank if you don't want google analytics integration.
google_analytics:  UA-408430-5

feedback_email: gentleman1@gmail.com

markdown: redcarpet

# options for the redcarpet markdown processing. leave as is, especially the "with_toc_data" or the mini-toc won't appear.
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# put all files or directories that you want to exclude from your project here.
exclude:
  - _drafts
  - bower_components
  - .idea
  - _site

# this enables the tooltip collection.
collections:
  tooltips:
    output: true

# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      tooltip: true
      search: true

sass:
    sass_dir: _sass

# if you want to show a label on each page indicating the audience that can see the content, put true here.
show_audience_label: true

# is this a print build? if so, put true. otherwise, false.
print: false
